
spring:
  config:
    activate:
      on-profile: dev
message: Bienvenue en dev

greeting:
  message: toto

---

spring:
  config:
    activate:
      on-profile: prod
message: Bienvenue en prod

greeting:
  message: tata