
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:demo
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

message: Bienvenue en dev

greeting:
  message: toto

---

spring:
  config:
    activate:
      on-profile: prod
message: Bienvenue en prod

greeting:
  message: tata